version: '3.9'

services:
  app:
    image: mybot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybot
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  db:
    image: postgres:16
    container_name: mybot_db
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
